name: Gatsby Application Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Gatsby Application
    runs-on: ubuntu-latest
    steps:

      - name: Get Linux Version
        run: lsb_release -a

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "18.3.0"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install Gatsby
        run: npm install -g gatsby-cli
      
      - name: Build Gatsby
        run: gatsby build

      - name: Verify the Build Successful
        run: ls -la public 
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ssh_private_key }}"> ~/.ssh/deploy_key
          sudo chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.host }}" > ~/.ssh/known_hosts

      - name: Copy public folder to server
        run: scp -r -i ~/.ssh/deploy_key public azureuser@20.84.97.218:/home/azureuser/public